CREATE TABLE DOCTORS (
    DOCTOR_ID NUMBER(10) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL ,
    LAST_NAME VARCHAR(255) NOT NULL ,
    EMAIL VARCHAR(255) NOT NULL ,
    PHONE VARCHAR(20) NOT NULL,
    BLOOD_GROUP VARCHAR(20),
    isDONOR VARCHAR(1),
    SPECIALIZATION VARCHAR(255),
    DEGREES VARCHAR(255)
);

ALTER TABLE DOCTORS ADD(
    CONSTRAINT doctors_pk PRIMARY KEY (DOCTOR_ID)
    );

CREATE SEQUENCE DOCTOR_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DOCTOR_BIR BEFORE INSERT ON DOCTORS
    FOR EACH ROW
    BEGIN
        SELECT DOCTOR_SEQ.nextval
        INTO :NEW.DOCTOR_ID
        FROM DUAL;
    end;
