CREATE TABLE USERS (
    USER_ID NUMBER(10) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL ,
    LAST_NAME VARCHAR(255) NOT NULL ,
    EMAIL VARCHAR(255) NOT NULL ,
    PHONE VARCHAR(20) NOT NULL,
    BLOOD_GROUP VARCHAR(20),
    isDONOR VARCHAR(1)
);

ALTER TABLE USERS ADD(
    CONSTRAINT user_pk PRIMARY KEY (USER_ID)
    );

CREATE SEQUENCE USER_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER USER_BIR BEFORE INSERT ON USERS
    FOR EACH ROW
    BEGIN
        SELECT USER_SEQ.nextval
        INTO :NEW.USER_ID
        FROM DUAL;
    end;
